# SyftBox Privacy Filter App Manifest
# Provides privacy-preserving LLM filtering for sensitive documents

name: syftbox-privacy-filter
version: 1.0.0
description: "Privacy-preserving LLM filter for protecting sensitive document content"
author: "Matthew Prewitt <mtprewitt@gmail.com>"

# Dependencies
requires:
  python: ">=3.9"
  syftbox: ">=0.2.0"

# Python dependencies
dependencies:
  - "pyyaml>=6.0"
  - "numpy>=1.24.0" 
  - "scikit-learn>=1.3.0"
  - "sentence-transformers>=2.2.0"
  - "transformers>=4.30.0"
  - "torch>=2.0.0"
  - "ollama>=0.1.0"

# SyftBox permissions requested
permissions_requested:
  read:
    - "datasites/*/private/.privacy_instructions/**"  # Read privacy rules
    - "datasites/*/private/*.txt"                     # Read protected documents
    - "datasites/*/private/*.md" 
    - "datasites/*/private/*.json"
    - "datasites/*/private/*.yaml"
  write:
    - "datasites/*/private/.privacy_audit/**"        # Write audit logs
    - "datasites/*/private/.privacy_cache/**"        # Cache filtered responses
  admin:
    - "apps/syftbox-privacy-filter/**"               # Manage own app data

# App configuration
config:
  # Privacy filter settings
  privacy:
    default_protection_level: "high"
    enable_audit_logging: true
    enable_integrity_checks: true
    
  # LLM settings
  llm:
    default_model: "llama3.2:3b"  # Lightweight local model
    max_context_length: 4096
    temperature: 0.1  # Low temperature for consistent privacy filtering
    
  # Information-theoretic settings
  entropy:
    enable_tracking: true
    precision_bits: 16
    
  # Communication settings
  api:
    host: "127.0.0.1"
    port: 8083
    protocol: "http"
    
# Entry points
entry_points:
  main: "main.py"
  
# Startup configuration
startup:
  auto_start: true
  restart_policy: "on-failure"
  
# Health checks
health_check:
  enabled: true
  endpoint: "/health"
  interval_seconds: 30

# Resource limits
resources:
  memory_limit_mb: 2048
  cpu_limit_cores: 2.0
  disk_limit_mb: 1024

# Security settings
security:
  enable_signature_verification: true
  require_https: false  # Local communication only
  rate_limiting:
    requests_per_minute: 100
    burst_limit: 20

# Metadata
metadata:
  tags: ["privacy", "llm", "filter", "protection", "security"]
  category: "privacy-tools"
  license: "MIT"
  homepage: "https://github.com/mtprewitt/syftbox-privacy-filter"
  documentation: "https://github.com/mtprewitt/syftbox-privacy-filter/blob/main/README.md"
  
created_date: "2025-01-11"
schema_version: "1.0"